services:
  better:
    image: simplicitely/better
    environment:
      - RUST_LOG=better=debug
      - BETTER_PERSISTENCE=postgres
      - BETTER_POSTGRES_DATNAME=better_db
      - BETTER_POSTGRES_HOST=database
      - BETTER_POSTGRES_PASSWORD=password
      - BETTER_CLIENTS=stub
      - BETTER_STUBDATA_FILE=/stubdata
    ports:
      - '8000:8000'
    configs:
      - stubdata
    depends_on:
      database:
        condition: service_healthy
  database:
    build: database
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-U', 'postgres']
      interval: 20s
      timeout: 30s
      retries: 5
configs:
  stubdata:
    file: ${BETTER_STUBDATA_FILE:-testdata/market_stub.json}
